routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminIndex'])->name('adminIndex');


Route::prefix('admin-games-managment')->name('admin.')->middleware(['admin'])->group( function ()
{
    Route::resource('games', App\Http\Controllers\Admin\GamesController::class);

    Route::get('/games/addToStock/{game}', [App\Http\Controllers\Admin\GamesController::class, 'addToStock'])->name('games.addToStock');
    Route::patch('/games/connectStore/{game}', [App\Http\Controllers\Admin\GamesController::class, 'connectStore'])->name('games.connectStore');
});

Route::prefix('user-cart')->name('user-cart.')->middleware(['auth'])->group( function ()
{
    Route::get('addToCart/{inventory}', [App\Http\Controllers\User\UserCartController::class,'addToCart'])->name('addToCart');
    Route::get('cartView', [App\Http\Controllers\User\UserCartController::class,'cartView'])->name('cartView');
    Route::get('cartBuy', [App\Http\Controllers\User\UserCartController::class,'cartBuy'])->name('cartBuy');
});

Route::prefix('user-profile')->name('user-profile.')->middleware(['auth'])->group( function ()
{
    Route::get('profile', [App\Http\Controllers\User\OrdersController::class,'orders'])->name('profile');

});


Route::prefix('admin-categories-managment')->name('admin.')->group( function ()
{
    Route::resource('category', App\Http\Controllers\Admin\CategoriesController::class)->except('edit','update','show','destroy')->middleware(['admin']);

});

Route::prefix('admin-stores-managment')->name('admin.')->group( function ()
{
    Route::resource('store', App\Http\Controllers\Admin\StoreController::class)->except('edit','update','show','destroy')->middleware(['admin']);
});

resources/views/admin/home.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
        <div class="row banner">

            <div class="col-md-12 mt-5">

                <div class="list-group">

                    <div class="list-group-item">
                        <div class="row-content">
                            <h5><i class="far fa-grin-tongue mb-3"></i> Manage Categories</h5>
                            <a href="{{ route('admin.category.index') }} " class="btn btn-info">All Categories</a>
                            <a href="{{ route('admin.category.create') }}" class="btn btn-success">Add a new category</a>
                        </div>
                    </div>

                    <div class="list-group-separator"></div>

                    <div class="list-group-separator"></div>

                        <div class="list-group-item">
                            <div class="row-content">
                                <h5><i class="fas fa-file-signature mb-3"></i> Manage Games</h5>
                                <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>
                                <a href="{{ route('admin.games.create') }}" class="btn btn-success">Add a new Game</a>
                            </div>
                        </div>

                    <div class="list-group-separator"></div>

                        <div class="list-group-item">
                            <div class="row-content">
                                <h5><i class="fas fa-cogs mb-3"></i> Manage Stores</h5>
                                <a href="{{ route('admin.store.index') }} " class="btn btn-info">All Stores</a>
                                <a href=" {{ route('admin.store.create') }}" class="btn btn-success">Add a new store</a>
                            </div>
                        </div>

                    <div class="list-group-separator"></div>
                </div>

            </div>

        </div>
    </div>
@endsection