routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminIndex'])->name('adminIndex');


Route::prefix('admin-games-managment')->name('admin.')->middleware(['admin'])->group( function ()
{
    Route::resource('games', App\Http\Controllers\Admin\GamesController::class);

    Route::get('/games/addToStock/{game}', [App\Http\Controllers\Admin\GamesController::class, 'addToStock'])->name('games.addToStock');
    Route::patch('/games/connectStore/{game}', [App\Http\Controllers\Admin\GamesController::class, 'connectStore'])->name('games.connectStore');
});

Route::prefix('user-cart')->name('user-cart.')->middleware(['auth'])->group( function ()
{
    Route::get('addToCart/{inventory}', [App\Http\Controllers\User\UserCartController::class,'addToCart'])->name('addToCart');
    Route::get('cartView', [App\Http\Controllers\User\UserCartController::class,'cartView'])->name('cartView');
    Route::get('cartBuy', [App\Http\Controllers\User\UserCartController::class,'cartBuy'])->name('cartBuy');
});

Route::prefix('user-profile')->name('user-profile.')->middleware(['auth'])->group( function ()
{
    Route::get('profile', [App\Http\Controllers\User\OrdersController::class,'orders'])->name('profile');

});


Route::prefix('admin-categories-managment')->name('admin.')->group( function ()
{
    Route::resource('category', App\Http\Controllers\Admin\CategoriesController::class)->except('edit','update','show','destroy')->middleware(['admin']);

});

Route::prefix('admin-stores-managment')->name('admin.')->group( function ()
{
    Route::resource('store', App\Http\Controllers\Admin\StoreController::class)->except('edit','update','show','destroy')->middleware(['admin']);
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="bg-white shadow-sm navbar navbar-expand-md navbar-light">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Store DS
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <ul class="navbar-nav ms-auto">
                        @guest

                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif

                        @else

                            <li class="nav-item dropdown">

                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="{{ route('user-profile.profile') }}">Profilo</a>

                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>

                                </div>

                            </li>

                            <form class="d-flex" action=" {{ route('user-cart.cartView') }}" method="GET">
                                <button class="btn btn-outline-dark" type="submit">
                                    <i class="bi-cart-fill me-1"></i>
                                    Cart
                                    <span class="text-white badge bg-dark ms-1 rounded-pill"> {{ $cart->inventories_count }}</span>
                                </button>
                            </form>



                            @if(Auth::user()->hasRole('admin'))

                                <li class="nav-item dropdown">

                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        Gestione
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                        <a class="dropdown-item" href="{{ route('adminIndex') }} "> Admin </a>

                                    </div>

                                </li>
                            @endif

                        @endguest
                    </ul>

                </div>

            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>


        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>

    </div>
</body>
</html>