routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminIndex'])->name('adminIndex');


Route::prefix('admin-games-managment')->name('admin.')->middleware(['admin'])->group( function ()
{
    Route::resource('games', App\Http\Controllers\Admin\GamesController::class);

    Route::get('/games/addToStock/{game}', [App\Http\Controllers\Admin\GamesController::class, 'addToStock'])->name('games.addToStock');
    Route::patch('/games/connectStore/{game}', [App\Http\Controllers\Admin\GamesController::class, 'connectStore'])->name('games.connectStore');
});

Route::prefix('user-cart')->name('user-cart.')->middleware(['auth'])->group( function ()
{
    Route::get('addToCart/{inventory}', [App\Http\Controllers\User\UserCartController::class,'addToCart'])->name('addToCart');
    Route::get('cartView', [App\Http\Controllers\User\UserCartController::class,'cartView'])->name('cartView');
    Route::get('cartBuy', [App\Http\Controllers\User\UserCartController::class,'cartBuy'])->name('cartBuy');
});

Route::prefix('user-profile')->name('user-profile.')->middleware(['auth'])->group( function ()
{
    Route::get('profile', [App\Http\Controllers\User\OrdersController::class,'orders'])->name('profile');

});


Route::prefix('admin-categories-managment')->name('admin.')->group( function ()
{
    Route::resource('category', App\Http\Controllers\Admin\CategoriesController::class)->except('edit','update','show','destroy')->middleware(['admin']);

});

Route::prefix('admin-stores-managment')->name('admin.')->group( function ()
{
    Route::resource('store', App\Http\Controllers\Admin\StoreController::class)->except('edit','update','show','destroy')->middleware(['admin']);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable =
    [
        'name',
    ];


    public function games() //relazione n gategory n games
    {
        return $this->belongsToMany('App\Models\Game','games_categories','category_id','game_id');
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('admin.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        try
        {
            DB::beginTransaction();

                $category = Category::create([
                    'name'  => $request->name,
                ]);

            DB::commit();

                session()->flash('success','La nuova categoria è stata aggiunta');
                return redirect()->route('admin.category.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Non è stato possibile aggiungere la nuova categoria'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }
    }

}

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
 <div class="container col-md-10 col-md-offset-2">
        <div class="mt-5 card">
            <div class="card-header d-flex justify-content-between ">
                <h5 class="float-left">Create a new category</h5>
                <a href="{{ route('admin.category.index') }}" class="btn btn-info">All Categories</a>
            </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @include('components.message')

            <div class="mt-2 card-body">
                <form method="post" action="{{ route('admin.category.store') }}">
                    @csrf

                    <div class="form-group">
                        <label for="name" class="col-lg-12 control-label">name</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{old('name') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-10 col-md-offset-2">
    <div class="card mt-5">

        <div class="card-header d-flex justify-content-between">

            <h5 class="float-left">All Categories</h5>
            <h5 class="float-right"> <a href="{{ route('admin.category.create') }}" class="btn btn-success">Add category</a> </h5>
            <a href="{{ route('admin.category.index') }}" class="btn btn-info">All categories</a>

        </div>

        <div class="content">

            @include('components.message')

            <div class="table-responsive">
                <table class="table">

                    <thead>
                        <tr>

                            <th>name</th>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach($categories as $category)

                            <tr>

                                <td>{{ $category->name }}</td>

                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
@endsection