routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/admin', [App\Http\Controllers\HomeController::class, 'adminIndex'])->name('adminIndex');


Route::prefix('admin-games-managment')->name('admin.')->middleware(['admin'])->group( function ()
{
    Route::resource('games', App\Http\Controllers\Admin\GamesController::class);

    Route::get('/games/addToStock/{game}', [App\Http\Controllers\Admin\GamesController::class, 'addToStock'])->name('games.addToStock');
    Route::patch('/games/connectStore/{game}', [App\Http\Controllers\Admin\GamesController::class, 'connectStore'])->name('games.connectStore');
});

Route::prefix('user-cart')->name('user-cart.')->middleware(['auth'])->group( function ()
{
    Route::get('addToCart/{inventory}', [App\Http\Controllers\User\UserCartController::class,'addToCart'])->name('addToCart');
    Route::get('cartView', [App\Http\Controllers\User\UserCartController::class,'cartView'])->name('cartView');
    Route::get('cartBuy', [App\Http\Controllers\User\UserCartController::class,'cartBuy'])->name('cartBuy');
});

Route::prefix('user-profile')->name('user-profile.')->middleware(['auth'])->group( function ()
{
    Route::get('profile', [App\Http\Controllers\User\OrdersController::class,'orders'])->name('profile');

});


Route::prefix('admin-categories-managment')->name('admin.')->group( function ()
{
    Route::resource('category', App\Http\Controllers\Admin\CategoriesController::class)->except('edit','update','show','destroy')->middleware(['admin']);

});

Route::prefix('admin-stores-managment')->name('admin.')->group( function ()
{
    Route::resource('store', App\Http\Controllers\Admin\StoreController::class)->except('edit','update','show','destroy')->middleware(['admin']);
});

app/Models/Game.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    use HasFactory;

    protected $fillable =
    [
        'name',
        'image',
        'quantity',
        'softwareHouse',
    ];

    protected $with =
    [
        'categories'
    ];

    public function categories() //relazione n a n categories
    {
        return $this->belongsToMany('App\Models\Category','games_categories','game_id','category_id');
    }

    public function inventory() //relazione 1 game a n inventory
    {
        return $this->hasMany('App\Models\Inventory','game_id','id');
    }
}

app/Http/Controllers/Admin/GamesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConnectStoresRequest;
use App\Http\Requests\GameStoreRequest;
use App\Http\Requests\UpdateGameRequest;
use App\Models\Category;
use App\Models\Game;
use App\Models\Inventory;
use App\Models\Store;
use App\Traits\ImgManageTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;

class GamesController extends Controller
{
    use ImgManageTrait;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $games = Game::with(['inventory','categories'])->orderBy('created_at','desc')->get();

        return view('admin.games.index',compact('games'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.games.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GameStoreRequest $request)
    {
        try
        {
            DB::beginTransaction();

                $game = Game::create(
                    [
                        'name' => $request->name,
                        'quantity' => $request->quantity,
                        'softwareHouse' => $request->softwareHouse,
                    ]
                );

                $game->categories()->sync($request->categories);

                if($request->hasFile('image'))
                {
                    $this->addImage($request->image, $game);
                }

            DB::commit();
                session()->flash('success','Il nuovo gioco è stato aggiunto');
                return redirect()->route('admin.games.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Non è stato possibile aggiungere il gioco'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }
    }

    public function addToStock(Game $game)
    {
        $stores = Store::all();

        return view('admin.games.addToStock',compact('stores','game'));
    }

    public function connectStore(ConnectStoresRequest $request,Game $game)
    {
        try
        {
            DB::beginTransaction();

                if($game->inventory->count() < $game->quantity)
                {
                    $inventory =Inventory::create(
                        [
                            'price' => $request->price,
                        ]
                    );
                    $inventory->store()->associate($request->store);
                    $inventory->game()->associate($game->id);
                    $inventory->save();
                }
                else
                {
                    $errors =
                    [
                        'error_message' => 'Limite massimo raggiunto'
                    ];
                    session()->flash('error',$errors);
                    return redirect()->route('admin.games.show',$game);
                }


            DB::commit();
            session()->flash('success','Il gioco è stato connesso allo store');
            return redirect()->route('admin.games.show',$game);
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nell\'inserimento dello store'
            ];
            session()->flash('error',$errors);
            return redirect()->route('admin.games.show',$game);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Games  $games
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {

        $inventory = Inventory::with(['store','game.categories'])->where('game_id',$game->id)->get();

        return view('admin.games.show',compact('game','inventory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Games  $games
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        if(!$game)
        {
            $errors =
            [
                'error_message' => 'Gioco non trovato'
            ];

            session()->flash('error',$errors);
            return redirect()->back();
        }
        else
        {
            $categories = Category::all();
            $selectedCategories = $game->categories->pluck('id')->toArray();
            return view('admin.games.edit',compact('game','categories','selectedCategories'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Games  $games
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateGameRequest $request, Game $game)
    {
        try
        {
            DB::beginTransaction();

               $game->update(
                   [
                    'name'                  => $request->name,
                    'softwareHouse'         => $request->softwareHouse,
                   ]
                );

                if($request->has('image'))
                {
                    $this->editImage($request->image,$game);
                }

                if($request->has('categories'))
                {
                    $game->categories()->sync($request->categories);
                }

                if($request->has('quantity'))
                {
                    if( $request->quantity >count($game->inventory) )
                    {
                        $game->update(
                            [
                                'quantity'  => $request->quantity
                            ]
                        );
                    }
                    else
                    {
                        $errors =
                        [
                            'error_message' => 'Non puoi inserire una quantità minore rispetto a giochi nell\'inventario clicca su manage inventory per vedere quante copie sono in vendità'
                        ];
                        session()->flash('error',$errors);
                        return redirect()->route('admin.games.index');
                    }
                }

            DB::commit();
                session()->flash('success','Il gioco è stato modificato');
                return redirect()->route('admin.games.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella modifica del gioco'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Games  $games
     * @return \Illuminate\Http\Response
     */
    public function destroy(Game $game)
    {
        if(file_exists( public_path('storage/'.$game->image) ) )
        {
            unlink(public_path('storage/'.$game->image));
        }

       // $game->delete(); softdelete
        session()->flash('success','Il gioco è stato eliminato');
        return redirect()->route('admin.games.index');
    }
}

resources/views/admin/games/addToStock.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-10 col-md-offset-2">
    <div class="card mt-5">

        <div class="card-header d-flex justify-content-between">

            <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>
            <a href="{{ route('admin.games.show',$game) }}" class="btn btn-info">Manage Inventory</a>

        </div>

        <div class="content">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @include('components.message')

            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>

                            <th>id</th>
                            <th>name</th>
                            <th>Image</th>
                            <th>categories</th>
                            <th>Software House</th>
                            <th>Stores linked</th>

                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td>{{ $game->name }}</td>

                            <td>  <img src="{{Storage::url($game->image)}}" class="img-fluid" style="width: 150px;height:100%">   </td>

                            <td>
                                @foreach ($game->categories as $category)
                                    <h5> {{ $category->name }}</h5>
                                @endforeach
                            </td>

                            <td>
                                {{ $game->softwareHouse }}
                            </td>

                            <td>

                                <form action="{{ route('admin.games.connectStore',$game) }}" method="post">
                                    @csrf
                                    @method('patch')

                                    <div class="form-group">

                                        <label for="stores" class="col-lg-12 control-label">stores</label>

                                        <div class="col-lg-12">

                                            @foreach($stores as $store)
                                                <label for="stores" class="control-label">{{ $store->name }}</label>
                                                <input  id="genderM" name="store" type="radio" value="{{ $store->id }}">
                                            @endforeach

                                        </div>

                                    </div>

                                    <div class="form-group">
                                        <label for="price" class="col-lg-12 control-label">price</label>
                                        <div class="col-lg-12">
                                            <input type="number" class="form-control" id="price" placeholder="price" name="price" value="{{old('price') }}">
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-lg-10 col-lg-offset-2">
                                            <button type="submit" class="btn btn-primary">add to store</button>
                                        </div>
                                    </div>

                                </form>

                            </td>

                        </tr>
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/games/create.blade.php
@extends('layouts.app')

@section('content')
 <div class="container col-md-10 col-md-offset-2">
        <div class="card mt-5">
            <div class="card-header ">
                <h5 class="float-left">Create a new post</h5>
                <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>
            </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @include('components.message')

            <div class="card-body mt-2">
                <form method="post" action="{{ route('admin.games.store') }}" enctype="multipart/form-data">
                    @csrf


                    <div class="form-group">
                        <label for="name" class="col-lg-12 control-label">name</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{old('name') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="quantity" class="col-lg-12 control-label">quantity</label>
                        <div class="col-lg-12">
                            <input type="number" class="form-control" id="quantity" placeholder="quantity" name="quantity" value="{{old('quantity') }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="softwareHouse" class="col-lg-12 control-label">Software House</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="softwareHouse" placeholder="softwareHouse" name="softwareHouse" value="{{old('softwareHouse') }}">
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="categories" class="col-lg-12 control-label">Categories</label>
                        <div class="col-lg-12">
                            <select class="form-control" id="category" name="categories[]" multiple>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="file" name="image" class="form-control">
                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/games/createStock.blade.php
@extends('layouts.app')

@section('content')
 <div class="container col-md-10 col-md-offset-2">
        <div class="card mt-5">
            <div class="card-header ">
                <h5 class="float-left">Create a new Game </h5>
                <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>
            </div>

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @include('components.message')

            <div class="card-body mt-2">
                <form method="post" action="{{ route('admin.games.store') }}" enctype="multipart/form-data">
                    @csrf



                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/games/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container col-md-10 col-md-offset-2">
        <div class="card mt-5">
            <div class="card-header ">
                <h5 class="float-left">Edit a game</h5>
                <div class="clearfix"></div>
            </div>
            <div class="card-body mt-2">
                <form method="post" action="{{ route('admin.games.update',$game) }}"  enctype="multipart/form-data">
                    @csrf
                    @method('patch')

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @include('components.message')

                    <div class="form-group">
                        <label for="name" class="col-lg-12 control-label">name</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{old('name') ? old('name') : $game->name}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="softwareHouse" class="col-lg-12 control-label">Software House</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" rows="3" id="softwareHouse" name="softwareHouse" value="{{old('softwareHouse') ? old('softwareHouse') : $game->softwareHouse}}">{{ $game->softwareHouse }}</textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="quantity" class="col-lg-12 control-label">Quantity</label>
                        <div class="col-lg-12">
                            <input type="number" class="form-control" id="quantity" placeholder="quantity" name="quantity" value="{{old('quantity') ? old('quantity') : $game->quantity}}">
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="categories" class="col-lg-12 control-label">Categories</label>

                        <div class="col-lg-12">
                            <select class="form-control" id="category" name="categories[]" multiple>

                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"  @if(in_array($category->id, $selectedCategories))   selected="selected" style="background-color: green;" @endif >
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-12" style="background-color: lightblue">
                        <img src="{{Storage::url($game->image)}}" class="img-fluid" style="width: 50%;height:300px">
                        <div class="form-group">
                            Cambia Immagine
                            <input type="file" name="image" class="form-control">
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <a href="{{ route('admin.games.index') }}"> Torna alla lista</a>
    </div>
@endsection

resources/views/admin/games/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-10 col-md-offset-2">
    <div class="card mt-5">

        <div class="card-header d-flex justify-content-between">

            <h5 class="float-left">All Games</h5>
            <h5 class="float-right"> <a href="{{ route('admin.games.create') }}" class="btn btn-success">Add a new Game</a> </h5>
            <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>

        </div>

        <div class="content">

            @include('components.message')

            <div class="table-responsive">
                <table class="table">

                    <thead>
                        <tr>

                            <th>name</th>
                            <th>Image</th>
                            <th>categories</th>
                            <th>quantiy</th>
                            <th>Software House</th>
                            <th>Inventory</th>
                            <th>Actions</th>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach($games as $game)

                            <tr>
                                <td>{{ $game->name }}</td>

                                <td>  <img src="{{Storage::url($game->image)}}" class="img-fluid" style="width: 150px;height:100%">   </td>

                                <td>
                                    @foreach ($game->categories as $category)
                                        <h5> {{ $category->name }}</h5>
                                    @endforeach
                                </td>

                                <td>  {{$game->quantity}} </a> </td>

                                <td>{{ $game->softwareHouse }}</td>

                                <td>
                                    <div class="d-flex flex-column justify-content-center">
                                        <a href="{{ route('admin.games.show',$game) }}" class="btn btn-info">Manage Inventory</a>
                                    </div>
                                </td>

                                <td>

                                    <form  style="display: inline-block" method="POST" action=" {{ route('admin.games.destroy',$game) }} ">
                                        @csrf
                                        @method('delete')

                                        <button type="submit"  class="">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </form>

                                    <a href=" {{ route('admin.games.edit',$game) }}"> <i class="fas fa-pencil-alt"></i> </a>


                                </td>

                            </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/games/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container col-md-10 col-md-offset-2">
    <div class="card mt-5">

        <div class="card-header d-flex justify-content-between">

            <div class="d-flex  justify-content-center align-items-center">
                @if($game->inventory->count() == $game->quantity )
                    <h5> Tutti i giochi di {{ $game->name }} sono statti aggiunti nei rispettivi stores</h5>
                @else

                    <h5> {{ $game->inventory->count() }} creati su   {{ $game->quantity }}</h5>
                    <a href="{{ route('admin.games.addToStock',$game) }}" class="btn btn-info">Add allo stock</a>

                @endif
            </div>

            <a href="{{ route('admin.games.index') }}" class="btn btn-info">All Games</a>

        </div>

        <div class="content">

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @include('components.message')

            <div class="table-responsive">
                <table class="table">

                    <thead>
                        <tr>

                            <th>id</th>
                            <th>name</th>
                            <th>Image</th>
                            <th>quantity</th>
                            <th>categories</th>
                            <th>Software House</th>

                        </tr>
                    </thead>

                    <tbody>
                            <tr>
                                <td>{{ $game->id }}</td>
                                <td>{{ $game->name }}</td>

                                <td>  <img src="{{Storage::url($game->image)}}" class="img-fluid" style="width: 150px;height:100%">   </td>
                                <td>{{ $game->quantity }}</td>

                                <td>
                                    @foreach ($game->categories as $category)
                                        <h5> {{ $category->name }}</h5>
                                    @endforeach
                                </td>

                                <td>
                                    {{ $game->softwareHouse }}
                                </td>


                            </tr>
                    </tbody>

                </table>
            </div>
            <h1>IN STOCK</h1>
            @foreach($inventory as $product)

                <div class="table-responsive">
                    <table class="table">

                        <thead>
                            <tr>

                                <th>id</th>
                                <th>name</th>
                                <th>Image</th>
                                <th>categories</th>
                                <th>Software House</th>
                                <th>store</th>
                                <th>price</th>

                            </tr>
                        </thead>

                        <tbody>
                                <tr>
                                    <td>{{ $product->id }}</td>
                                    <td>{{ $product->game->name }}</td>

                                    <td>  <img src="{{Storage::url($product->game->image)}}" class="img-fluid" style="width: 150px;height:100%">   </td>

                                    <td>
                                        @foreach ($product->game->categories as $category)
                                            <h5> {{ $category->name }}</h5>
                                        @endforeach
                                    </td>

                                    <td> {{ $product->game->softwareHouse }}  </td>

                                    <td> {{ $product->store->name }}  </td>
                                    <td> {{ $product->price }}  </td>

                                </tr>
                        </tbody>

                    </table>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection